### PR TITLE
Add tests for makeup lesson

### LINKED ISSUE #115: Add more extensive tests for MakeupLesson
To improve code coverage.

### PR DESCRIPTION
**Pull request by bryancheny**
Fixes #115

### CODE REVIEW

**Comment by dwsc37** [comment]
Do you plan on adding more tests to improve coverage? (Not saying you need to, just checking)

**Comment by bryancheny** [comment]
nah

**Comment by zzawook** [comment]
> is there a code coverage target we must hit? if not then no plans

The codecov report says the target is 74.62% to pass the coverage test, but i remember 2103T team expects about 85 or above. I think you might want to add more tests to hit the target.

**Review by audipras — APPROVED** [review]
LGTM!

**Pull request merged**
